/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import General.Connector;
import General.User;
import VicLib.Msg;
import java.awt.Color;

/**
 *
 * @author just_
 */
public class LoginFrame extends javax.swing.JFrame {

    boolean firstPassword = true;
    int yCoord;
    int xCoord;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        pnl_overlay.setBackground(new Color(0, 0, 0, 200));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_overlay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnl_login = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_password = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        label_x = new javax.swing.JLabel();
        bg_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GameLand Login");
        setName("loginFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_overlay.setBackground(new java.awt.Color(0, 0, 0));
        pnl_overlay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_overlayMouseDragged(evt);
            }
        });
        pnl_overlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_overlayMousePressed(evt);
            }
        });
        pnl_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 106, 195));
        jLabel4.setText("GameLand");
        pnl_overlay.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seu checkpoint é aqui.");
        pnl_overlay.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 580));

        pnl_login.setBackground(new java.awt.Color(32, 33, 35));

        lbl_user.setForeground(new java.awt.Color(60, 110, 180));
        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/login-user.png"))); // NOI18N
        lbl_user.setText("Usuário");

        txt_username.setBackground(new java.awt.Color(32, 33, 35));
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setBorder(null);
        txt_username.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        lbl_password.setForeground(new java.awt.Color(51, 52, 54));
        lbl_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/login-password.png"))); // NOI18N
        lbl_password.setText("Senha");

        txt_password.setBackground(new java.awt.Color(32, 33, 35));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setText("textodeteste");
        txt_password.setBorder(null);
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clickLoginButton(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(125, 90, 195));
        btn_login.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setLabel("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 64, 70));
        jLabel3.setText("Esqueceu a senha? Fale com o administrador.");

        label_x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_x.setForeground(new java.awt.Color(60, 110, 180));
        label_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/login-exit.png"))); // NOI18N
        label_x.setAlignmentY(0.0F);
        label_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_x.setMaximumSize(new java.awt.Dimension(16, 16));
        label_x.setMinimumSize(new java.awt.Dimension(30, 30));
        label_x.setPreferredSize(new java.awt.Dimension(16, 16));
        label_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_xMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_loginLayout.createSequentialGroup()
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_password)
                                    .addComponent(jSeparator2)
                                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_user)
                                    .addComponent(jSeparator1)
                                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_loginLayout.createSequentialGroup()
                        .addComponent(label_x, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_x, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(lbl_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        btn_login.getAccessibleContext().setAccessibleName("btn_login");

        getContentPane().add(pnl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 460, 580));

        bg_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/login-bg.png"))); // NOI18N
        bg_img.setAlignmentX(100.0F);
        bg_img.setAlignmentY(0.0F);
        getContentPane().add(bg_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void label_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_xMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_label_xMouseClicked

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        // TODO add your handling code here:

        if (firstPassword) {
            firstPassword = false;
            txt_password.setText(null);
        }

        lbl_password.setForeground(new Color(60, 110, 180));
        lbl_user.setForeground(new Color(51, 52, 54));
    }//GEN-LAST:event_txt_passwordFocusGained


    private void pnl_overlayMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_overlayMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xCoord, y - yCoord);
    }//GEN-LAST:event_pnl_overlayMouseDragged

    private void pnl_overlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_overlayMousePressed
        // TODO add your handling code here:
        xCoord = evt.getX();
        yCoord = evt.getY();
    }//GEN-LAST:event_pnl_overlayMousePressed

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        // TODO add your handling code here:
        lbl_user.setForeground(new Color(60, 110, 180));
        lbl_password.setForeground(new Color(51, 52, 54));
    }//GEN-LAST:event_txt_usernameFocusGained

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void clickLoginButton(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clickLoginButton
        // TODO add your handling code here:

        if (evt.getKeyCode() == 10) {
            login();
        }
    }//GEN-LAST:event_clickLoginButton

    private void login() {
        
        // Entra com dados
        String username = txt_username.getText();
        String password = String.valueOf(txt_password.getPassword());

        // Verifica validade
        if (!username.isEmpty() && !password.isEmpty()) {

            boolean success;
            success = User.selectUser(username, password);

            // Verifica se consta no banco de dados
            if (success) {
                openMainScreen();

            } else {
                Msg.error("Usuario ou senha inválidos.");
            }

        } else {
            Msg.alertValid("usuario ou senha");
        }
    }

    private void openMainScreen() {
        new ScreenFrame().setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_img;
    private java.awt.Button btn_login;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_x;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
