/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Employee;
import Classes.Game;
import General.Tools;
import General.User;
import VicLib.Msg;
import VicLib.ParseForm;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author just_
 */
public class ScreenFrame extends javax.swing.JFrame {

    int xCoord;
    int yCoord;

    Employee user = User.currentUser;

    JPanel selected = null;

    Color mainColor = new Color(38, 42, 52);
    Color mainHoverColor = new Color(29, 32, 43);
    Color mainSelected = new Color(38, 187, 135);
    Color mainHoverSelected = new Color(77, 219, 169);
    
    ArrayList<Game> games;
    

    public ScreenFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        updateTopBar();
        games = Game.selectGames();
    }

    void updateTopBar() {
        userLabel.setText(user.getFirstName());
        salesLabel.setText(String.valueOf(user.getSales()));
        
        if (user.getJob() == 1) {
            main_employees.setVisible(false);
            main_stock.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salesLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        menuPane = new javax.swing.JPanel();
        main_history = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        main_cart = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        main_stock = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        main_employees = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        main_logout = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        main_games = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submenuPanel = new javax.swing.JPanel();
        sub1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_search = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        dashPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gamesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GameLand");
        setName("mainFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topbar.setBackground(new java.awt.Color(38, 42, 52));
        topbar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        topbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topbarMouseDragged(evt);
            }
        });
        topbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topbarMousePressed(evt);
            }
        });
        topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/login-exit.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        topbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 20, -1));

        userLabel.setForeground(new java.awt.Color(0, 255, 0));
        userLabel.setText("!Usuário");
        topbar.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuário:");
        topbar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vendas:");
        topbar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        salesLabel.setForeground(new java.awt.Color(0, 255, 0));
        salesLabel.setText("!0");
        topbar.add(salesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Painel GameLand");
        topbar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        label_status.setForeground(new java.awt.Color(51, 255, 51));
        topbar.add(label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        getContentPane().add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 20));

        menuPane.setBackground(new java.awt.Color(38, 42, 52));
        menuPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_history.setBackground(new java.awt.Color(38, 42, 52));
        main_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_historyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main_historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                main_historyMouseExited(evt);
            }
        });
        main_history.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/dash-history.png"))); // NOI18N
        main_history.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("          Histórico");
        main_history.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 110, -1));

        menuPane.add(main_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 154, 120, 80));

        main_cart.setBackground(new java.awt.Color(38, 42, 52));
        main_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_cartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main_cartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                main_cartMouseExited(evt);
            }
        });
        main_cart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/dash-cart.png"))); // NOI18N
        main_cart.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("           Carrinho");
        main_cart.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 110, -1));

        menuPane.add(main_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, -1));

        main_stock.setBackground(new java.awt.Color(38, 42, 52));
        main_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_stockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main_stockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                main_stockMouseExited(evt);
            }
        });
        main_stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/dash-stock.png"))); // NOI18N
        main_stock.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("           Estoque");
        main_stock.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 110, -1));

        menuPane.add(main_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 120, 80));

        main_employees.setBackground(new java.awt.Color(38, 42, 52));
        main_employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_employeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main_employeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                main_employeesMouseExited(evt);
            }
        });
        main_employees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/dash-employee.png"))); // NOI18N
        main_employees.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("       Empregados");
        main_employees.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 110, -1));

        menuPane.add(main_employees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 120, 80));

        main_logout.setBackground(new java.awt.Color(38, 42, 52));
        main_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                main_logoutMouseExited(evt);
            }
        });
        main_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/dash-logout.png"))); // NOI18N
        main_logout.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("           Logout");
        main_logout.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 110, -1));

        menuPane.add(main_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 120, 80));

        main_games.setBackground(new java.awt.Color(38, 42, 52));
        main_games.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_gamesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main_gamesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                main_gamesMouseExited(evt);
            }
        });
        main_games.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/dash-games.png"))); // NOI18N
        main_games.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jogos");
        main_games.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        menuPane.add(main_games, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 80));

        getContentPane().add(menuPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 110, 520));

        submenuPanel.setBackground(new java.awt.Color(29, 32, 43));
        submenuPanel.setLayout(new java.awt.CardLayout());

        sub1.setBackground(new java.awt.Color(29, 32, 43));
        sub1.setOpaque(false);
        sub1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sub1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 10));

        txt_search.setBackground(new java.awt.Color(29, 32, 43));
        txt_search.setForeground(new java.awt.Color(255, 255, 255));
        txt_search.setBorder(null);
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });
        sub1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 200, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/sub-search.png"))); // NOI18N
        sub1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(29, 32, 43));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/sub-list.png"))); // NOI18N
        jButton2.setText("Atualizar lista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        sub1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 50));

        jButton5.setBackground(new java.awt.Color(29, 32, 43));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/sub-buy.png"))); // NOI18N
        jButton5.setText("Adicionar ao carrinho");
        sub1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 50));

        submenuPanel.add(sub1, "subgames");

        getContentPane().add(submenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 260, 520));

        dashPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 32, 43)));
        dashPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        gamesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gamesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(gamesTable);
        if (gamesTable.getColumnModel().getColumnCount() > 0) {
            gamesTable.getColumnModel().getColumn(0).setResizable(false);
            gamesTable.getColumnModel().getColumn(1).setResizable(false);
            gamesTable.getColumnModel().getColumn(2).setResizable(false);
            gamesTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        dashPanel.add(jPanel1, "gamesdisplay");
        jPanel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        dashPanel.add(jPanel2, "card3");

        getContentPane().add(dashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 660, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void topbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xCoord, y - yCoord);
    }//GEN-LAST:event_topbarMouseDragged

    private void topbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMousePressed
        // TODO add your handling code here:
        xCoord = evt.getX();
        yCoord = evt.getY();
    }//GEN-LAST:event_topbarMousePressed

    private void main_gamesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_gamesMouseEntered
        // TODO add your handling code here:
        mouseIn(main_games);
    }//GEN-LAST:event_main_gamesMouseEntered

    private void main_historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_historyMouseEntered
        // TODO add your handling code here:
        mouseIn(main_history);
    }//GEN-LAST:event_main_historyMouseEntered

    private void main_cartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_cartMouseEntered
        // TODO add your handling code here:
        mouseIn(main_cart);
    }//GEN-LAST:event_main_cartMouseEntered

    private void main_stockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_stockMouseEntered
        // TODO add your handling code here:
        mouseIn(main_stock);
    }//GEN-LAST:event_main_stockMouseEntered

    private void main_employeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_employeesMouseEntered
        // TODO add your handling code here:
        mouseIn(main_employees);
    }//GEN-LAST:event_main_employeesMouseEntered

    private void main_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_logoutMouseEntered
        // TODO add your handling code here:
        mouseIn(main_logout);
    }//GEN-LAST:event_main_logoutMouseEntered

    private void main_cartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_cartMouseExited
        // TODO add your handling code here:
        mouseOut(main_cart);
    }//GEN-LAST:event_main_cartMouseExited

    private void main_historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_historyMouseExited
        // TODO add your handling code here:
        mouseOut(main_history);
    }//GEN-LAST:event_main_historyMouseExited

    private void main_stockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_stockMouseExited
        // TODO add your handling code here:
        mouseOut(main_stock);
    }//GEN-LAST:event_main_stockMouseExited

    private void main_employeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_employeesMouseExited
        // TODO add your handling code here:
        mouseOut(main_employees);
    }//GEN-LAST:event_main_employeesMouseExited

    private void main_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_logoutMouseExited
        // TODO add your handling code here:
        mouseOut(main_logout);
    }//GEN-LAST:event_main_logoutMouseExited

    private void main_gamesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_gamesMouseExited
        // TODO add your handling code here:
        mouseOut(main_games);
    }//GEN-LAST:event_main_gamesMouseExited

    private void main_gamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_gamesMouseClicked
        // TODO add your handling code here:
        selectPanel(main_games);
        switchMenu(submenuPanel, "subgames");
        switchMenu(dashPanel, "gamedisplay");
        refreshGamesTable();
    }//GEN-LAST:event_main_gamesMouseClicked

    private void main_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_cartMouseClicked
        // TODO add your handling code here:
        selectPanel(main_cart);
        switchMenu(submenuPanel, "subcart");
    }//GEN-LAST:event_main_cartMouseClicked

    private void main_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_historyMouseClicked
        // TODO add your handling code here:
        selectPanel(main_history);
    }//GEN-LAST:event_main_historyMouseClicked

    private void main_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_stockMouseClicked
        // TODO add your handling code here:
        selectPanel(main_stock);
    }//GEN-LAST:event_main_stockMouseClicked

    private void main_employeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_employeesMouseClicked
        // TODO add your handling code here:
        selectPanel(main_employees);
    }//GEN-LAST:event_main_employeesMouseClicked

    private void main_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_logoutMouseClicked
        // TODO add your handling code here:
        selectPanel(main_logout);
    }//GEN-LAST:event_main_logoutMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        refreshGamesTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            String filter = txt_search.getText();
            searchFilter(filter);
        }
    }//GEN-LAST:event_txt_searchKeyPressed

    public void searchFilter(String filter) {
        filter = Tools.filterQuery(filter);
        
        games = Game.selectGames("name", filter);
        
        updateGameTable(games);        
        
    }
    
    public void updateGameTable(ArrayList<Game> games) {
        DefaultTableModel table = (DefaultTableModel) gamesTable.getModel();
        table.setRowCount(0);
        
        this.games.forEach((game) -> {
            table.addRow(new Object[]{
                game.getId(),
                game.getName(),
                game.getPrice(),
                game.getAmount()
            });
        });
        
        int rowAmount = table.getRowCount();
        label_status.setText("Jogos encontrados: " + String.valueOf(rowAmount));
    }
    
    public void refreshGamesTable() {
        games = Game.selectGames();

        updateGameTable(games);
    }
    
    private void switchMenu(JPanel top, String panel) {
        CardLayout card = (CardLayout) top.getLayout();
        card.show(top, panel);
    }
    
    
    private void selectPanel(JPanel panel) {
        unselectPanel();
        panel.setBackground(mainSelected);
        selected = panel;
    }
    
    private void unselectPanel() {
        if (selected != null)
            selected.setBackground(mainColor);
    }
    
    private void mouseOut(JPanel panel) {
        if (!(selected == panel)) {
            panel.setBackground(mainColor);
        }
    }

    private void mouseIn(JPanel panel) {
        if (!(selected == panel)) {
            panel.setBackground(mainHoverColor);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ScreenFrame screen = new ScreenFrame();
                screen.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashPanel;
    private javax.swing.JTable gamesTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_status;
    private javax.swing.JPanel main_cart;
    private javax.swing.JPanel main_employees;
    private javax.swing.JPanel main_games;
    private javax.swing.JPanel main_history;
    private javax.swing.JPanel main_logout;
    private javax.swing.JPanel main_stock;
    private javax.swing.JPanel menuPane;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JPanel sub1;
    private javax.swing.JPanel submenuPanel;
    private javax.swing.JPanel topbar;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
